version: '2'

services:
# Nginx :0  easy way :80 :D 
    web:
        image: nginx:latest
        container_name: allmn_nginx
        ports:
            - "80:80"
        volumes:
            - ./www:/www
            - /storage:/storage
            - ./nginx:/etc/nginx/conf.d
        networks:
            - network-front

# PHPs usei o build [diretorios] para instalar libs ;)
    php-7:
        build: php-fpm-7
        container_name: allmn_php-7
        volumes:
            - ./www:/www
            - /storage:/storage
        networks:
            - network-front
            - network-back
    php-5.6:
        build: php-fpm-5.6
        container_name: allmn_php-5.6
        volumes:
            - ./www:/www
            - /storage:/storage
        networks:
            - network-front
            - network-back

# BASE DE DADOS
    mysql-5.7:
        image: mysql:5.7
        container_name: allmn_mysql-5.7
        volumes:
            - mysql-5.7:/var/lib/mysql
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: root
        networks:
            - network-back
    mysql-5.5:
        image: mysql:5.5
        container_name: allmn_mysql-5.5
        volumes:
            - mysql-5.5:/var/lib/mysql
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: root
        networks:
            - network-back
    percona:
        image: percona
        container_name: allmn_percona
        volumes:
            - percona:/var/lib/mysql
        environment:
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: root
        networks:
            - network-back

# ACESSAR AS BASES http://127.0.0.1:8888/ ;)
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: allmn_phpmyadmin
        environment:
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8888:80
        volumes:
            - /sessions
        networks:
            - network-back

# Networks links internos para os services names ;)
networks:
    # basicamente o nginx e quem precisa dele.
    network-front:
        driver: bridge
    # basicamente o que NAO precisa do nginx.
    network-back:
        driver: bridge

# using volumes Docker [dir]
volumes:
    percona:
    mysql-5.7:
    mysql-5.5: