version: '2'

services:
# Nginx :0  easy way :80 :D 
    web:
        image: nginx:latest
        container_name: allmn_nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/includes.d:/etc/nginx/includes.d # dir usado para includes files nginx config
            - ./nginx/conf.d:/etc/nginx/conf.d
            - /storage:/storage # local dir [projects]
        networks:
            - network-front

# PHPs extends file: é a referencia :D assim deixo tudo separado
    php-7:
      restart: always
      extends:
        file: php/php.yml
        service: php-7

    php-5.6:
      restart: always
      extends:
        file: php/php.yml
        service: php-5.6

# BASE DE DADOS MySQL
    mysql-5.7:
        image: mysql:5.7
        container_name: allmn_mysql-5.7
        volumes:
            - mysql-5.7:/var/lib/mysql
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: root
        networks:
            - network-back
    mysql-5.5:
        image: mysql:5.5
        container_name: allmn_mysql-5.5
        volumes:
            - mysql-5.5:/var/lib/mysql
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: root
        networks:
            - network-back
    percona:
        image: percona
        container_name: allmn_percona
        volumes:
            - percona:/var/lib/mysql
        environment:
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: root
        networks:
            - network-back

# ACESSAR AS BASES http://127.0.0.1:8888/ ;)
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: allmn_phpmyadmin
        environment:
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8888:80
        volumes:
            - /sessions
        networks:
            - network-back


# Networks links internos para os services names ;)
networks:
    # basicamente o nginx e quem precisa dele.
    network-front:
        driver: bridge
    # basicamente o que NAO precisa do nginx.
    network-back:
        driver: bridge

# using volumes Docker [dir]
volumes:
    percona:
    mysql-5.7:
    mysql-5.5: