version: '2'

services:
    web:
        image: nginx:latest
        container_name: allmn_nginx
        ports:
            - "80:80"
        volumes:
            - ./storage:/storage
            - ./nginx:/etc/nginx/conf.d
        networks:
            - code-network
    php-7:
        build: php-fpm-7
        container_name: allmn_php-7
        volumes:
            - ./storage:/storage
        networks:
            - code-network
    php-5.6:
        build: php-fpm-5.6
        container_name: allmn_php-5.6
        volumes:
            - ./storage:/storage
        networks:
            - code-network
    mysql-5.7:
        image: mysql:5.7
        container_name: allmn_mysql-5.7
        volumes:
         - /var/lib/mysql5.7
        environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=database
        networks:
            - code-network
    mysql-5.5:
        image: mysql:5.5
        container_name: allmn_mysql-5.5
        volumes:
         - /var/lib/mysql5.5
        environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=database
        networks:
            - code-network
networks:
    code-network:
        driver: bridge