version: '2'

services:
# BASE DE DADOS MySQL 
    mysql-5.7:
        image: mysql:5.7
        restart: always
        container_name: work_mysql-5.7
        volumes:
            - ./data/mysql-5.7:/var/lib/mysql
            - ./dumps:/dumps
            #- ./my.conf:/etc/mysql/my.cnf
        ports:
            - "3306:3306"
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: root
        networks:
            - network-back

    percona:
        image: percona
        restart: always
        container_name: work_percona
        volumes:
            - ./data/percona:/var/lib/mysql
            - ./dumps:/dumps
            #- ./my.conf:/etc/mysql/my.cnf
        ports:
            - "3306:3306"
        environment:
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: root
        networks:
            - network-back
